export type Role = 'ADMIN' | 'ASSET_MANAGER' | 'DEPARTMENT_HEAD' | 'EMPLOYEE';

export type Permission = 
  // Admin
  | 'MANAGE_DEPARTMENTS'
  | 'MANAGE_CATEGORIES'
  | 'PROMOTE_EMPLOYEES'
  | 'VIEW_ALL_REPORTS'
  | 'CREATE_AUDIT'
  | 'ASSIGN_ROLES'
  // Shared Management
  | 'VIEW_ALL_ASSETS'
  | 'VIEW_ALL_MAINTENANCE'
  | 'VIEW_ALL_BOOKINGS'
  // Asset Manager
  | 'REGISTER_ASSET'
  | 'ALLOCATE_ASSET'
  | 'APPROVE_TRANSFER'
  | 'APPROVE_MAINTENANCE'
  | 'APPROVE_RETURN'
  | 'RESOLVE_AUDIT'
  | 'VIEW_ASSET_REPORTS'
  // Department Head
  | 'VIEW_DEPARTMENT_ASSETS'
  | 'APPROVE_DEPARTMENT_TRANSFER'
  | 'APPROVE_DEPARTMENT_ALLOCATION'
  | 'BOOK_FOR_DEPARTMENT'
  | 'VIEW_DEPARTMENT_REPORTS'
  // Employee
  | 'VIEW_MY_ASSETS'
  | 'BOOK_RESOURCE'
  | 'RAISE_MAINTENANCE'
  | 'REQUEST_TRANSFER'
  | 'REQUEST_RETURN';

export const ROLE_PERMISSIONS: Record<Role, Permission[]> = {
  ADMIN: [
    'MANAGE_DEPARTMENTS', 'MANAGE_CATEGORIES', 'PROMOTE_EMPLOYEES', 
    'VIEW_ALL_REPORTS', 'CREATE_AUDIT', 'ASSIGN_ROLES',
    'VIEW_ALL_ASSETS', 'VIEW_ALL_MAINTENANCE', 'VIEW_ALL_BOOKINGS',
    'REGISTER_ASSET', 'ALLOCATE_ASSET', 'APPROVE_TRANSFER', 
    'APPROVE_MAINTENANCE', 'APPROVE_RETURN', 'RESOLVE_AUDIT', 'VIEW_ASSET_REPORTS'
  ],
  ASSET_MANAGER: [
    'REGISTER_ASSET', 'ALLOCATE_ASSET', 'APPROVE_TRANSFER', 
    'APPROVE_MAINTENANCE', 'APPROVE_RETURN', 'RESOLVE_AUDIT', 
    'VIEW_ASSET_REPORTS', 'VIEW_ALL_ASSETS', 'VIEW_ALL_MAINTENANCE', 'VIEW_ALL_BOOKINGS'
  ],
  DEPARTMENT_HEAD: [
    'VIEW_DEPARTMENT_ASSETS', 'APPROVE_DEPARTMENT_TRANSFER', 
    'APPROVE_DEPARTMENT_ALLOCATION', 'BOOK_FOR_DEPARTMENT', 
    'VIEW_DEPARTMENT_REPORTS', 'BOOK_RESOURCE', 'RAISE_MAINTENANCE', 
    'REQUEST_TRANSFER', 'REQUEST_RETURN'
  ],
  EMPLOYEE: [
    'VIEW_MY_ASSETS', 'BOOK_RESOURCE', 'RAISE_MAINTENANCE', 
    'REQUEST_TRANSFER', 'REQUEST_RETURN'
  ]
};

export function hasPermission(userRole: Role, permission: Permission): boolean {
  if (!userRole || !ROLE_PERMISSIONS[userRole]) return false;
  return ROLE_PERMISSIONS[userRole].includes(permission);
}
